name: Perf

on:
  workflow_dispatch:
  schedule:
    # Monthly at 05:00 UTC (14:00 JST) on the first day of the month idk if this is necessary
    - cron: "0 5 1 * *"

concurrency:
  group: perf-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  perf:
    name: Benchmarks • Ubuntu • py3.12
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install project (dev)
        run: |
          uv pip install -e .[dev]

      - name: Run perf suite
        run: |
          pytest -q -m perf --benchmark-save=ci-latest --benchmark-min-time=0.2

      - name: Upload benchmark artifacts
        uses: actions/upload-artifact@v4
        with:
          name: perf-benchmarks
          path: ./.benchmarks/**
