name: Publish (PyPI • Trusted Publishing)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    environment: pypi # must match the Environment name on your PyPI Trusted Publisher entry

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v4
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Build sdist/wheel
        run: |
          uv build
          ls -l dist

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
